[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm install && npx prisma generate"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
