[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
workingDirectory = "backend"
cmds = ["npm install", "npx prisma generate"]

[start]
workingDirectory = "backend"
cmd = "npx prisma migrate deploy && npm start"
