[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm ci", "cd backend && npx prisma generate"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
