[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
workingDirectory = "backend"
cmds = ["npm ci", "npx prisma generate"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
workingDirectory = "backend"
cmd = "npx prisma migrate deploy && npm start"
