services:
  - type: web
    name: xeno-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: xeno-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false

  - type: web
    name: xeno-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://xeno-backend.onrender.com

databases:
  - name: xeno-db
    plan: free
    databaseName: xeno
    user: xeno_user
